site_name: Premier Langage
site_author: Q. Coumes, D. Revuz, M. Cisse, C. Callé
repo_url: https://github.com/PremierLangage/premierlangage
edit_uri: tree/master/server/serverpl/documentation/mkdocs/docs

nav:
- Home: 'index.md'
- Ecrire un exercice:
    - 'Le Langage': 'langage_pl.md'
    - 'Construction': 'construction.md'
    - 'Affichage / Formulaire': 'affichage.md'
    - 'Évaluation': 'evaluation.md'
    - 'Paramètres': 'pl_settings.md'
- Ecrire une Feuille d'Exercices: 'pltp.md'
- Templates:
    - 'Index': 'template_index.md'
    - 'Java': 'template_java.md'
- Builders:
    - 'Index': 'builder_index.md'
    - 'Before': 'before.md'
    - 'Build': 'build.md'
- Formulaires:
    - 'Index': 'form_index.md'
    - 'Éditeur de Texte': 'text_editor.md'
- Graders:
    - 'Index': 'grader_index.md'
    - 'Evaluator': 'evaluator.md'
    - 'Evalfunc': 'evalfunc.md'
    - 'Java': 'grader_java.md'

theme:
    name: null
    custom_dir: 'custom'

site_dir: ../templates/documentation/doc
